---
# yamllint disable rule:line-length
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^(\..*|README.md|\.pre-commit-config\.yaml|\.yamllint)
      - id: ruff-format
        files: >
          ^((custom_components|pylint|script|tests)/.+)?[^/]+\.(py|pyi)$
        exclude: ^(\..*|README.md|\.pre-commit-config\.yaml|\.yamllint)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^(\..*|README.md|\.pre-commit-config\.yaml|\.yamllint)
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.6.0
    hooks:
      - id: python-typing-update
        stages: [manual]
        args:
          - --py312-plus
          - --force
          - --keep-updates
        files: >
          ^(custom_components|tests|script)/.+\.py$
        exclude: ^(\..*|README.md|\.pre-commit-config\.yaml|\.yamllint)
