---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^(.github/|README.md)
      - id: ruff-format
        files: ^((custom_components|pylint|script|tests)/.+)?[^/]+\.(py|pyi)$
        exclude: ^(.github/|README.md)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=additionals,alle,alot,astroid,bund,caf,convencional,
            currenty,datas,farenheit,falsy,fo,frequence,haa,hass,iif,incomfort,ines,
            ist,nam,nd,pres,pullrequests,resset,rime,ser,serie,te,technik,ue,unsecure,
            vor,withing,zar
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: ^(.github/|README.md)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^(.github/|README.md)
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.6.0
    hooks:
      - id: python-typing-update
        stages: [manual]
        args:
          - --py312-plus
          - --force
          - --keep-updates
        files: ^(custom_components|tests|script)/.+\.py$
        exclude: ^(.github/|README.md)
