repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.15.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/pre-commit/mirrors-ruff
    rev: v0.0.241
    hooks:
      - id: ruff
        args: [--fix]