blueprint:
  name: Divera Alarm Automatisierung (Deutsch)
  description: Automatisiere Aktionen bei Auslösung eines Divera-Alarms.
  domain: automation
  author: DeinName
  source_url: https://github.com/DeinGitHubRepo/your-blueprint-de.yaml
  homeassistant:
    min_version: 2022.4.0
  input:
    divera_sensormodul:
      name: Divera Alarmsensor
      description: Der Sensor, der den aktuellen Divera-Alarmstatus anzeigt.
      selector:
        entity:
          integration: divera
          domain:
            - sensor
          multiple: true
    selbstadressiert:
      name: Selbstadressiert
      description: Überprüfen, ob der Alarm mich direkt betrifft.
      selector:
        boolean: {}
      default: true
    abbruch_keyword:
      name: (optional) Abbruch-Wort
      description:
        "(optional) Alarmtitel/Keyword, bei dem die Aktion nicht ausgelöst werden soll. Zum Beispiel: Probealarm"
      default: ""
      selector:
        text:
          multiline: false
          multiple: false
    auszuführende_aktion:
      name: Aktion
      description: Was soll passieren, wenn ein neuer Divera-Alarm ausgelöst wird?
      selector:
        action: {}
mode: parallel
max: 10
variables:
  selbstadressiert: !input selbstadressiert
trigger:
  - platform: state
    entity_id: !input divera_sensormodul
    attribute: id
    not_to:
      - unknown
condition:
  condition: and
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: !input divera_sensormodul
          state:
            - !input abbruch_keyword
            - unknown
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ not selbstadressiert }}"
        - condition: state
          entity_id: !input divera_sensormodul
          attribute: selbstadressiert
          state: true
    - condition: state
      entity_id: !input divera_sensormodul
      attribute: closed
      state: false
action:
  - service: notify.notify
    data:
      message: "Alarm ausgelöst! Bitte prüfen Sie sofort!"
