name: Feature Request
description: Schlage eine neue Funktion vor
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Danke für deinen Feature Request! Bitte fülle alle Felder aus.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Beschreibe das Problem das diese Feature lösen würde
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Vorgeschlagene Lösung
      description: Beschreibe deine Idee für die Lösung
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Beschreibe alternative Lösungen oder Features
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Zusätzlicher Kontext
      description: Weitere Informationen oder Screenshots
    validations:
      required: false
