---
name: ✅ HACS Validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: "✅ HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6

      - name: 🚀 Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
